### ISSUE TITLE
bug in api

### ISSUE THREAD

**Issue by DevopsTech10** [DevopsTech10/RestApi#5]
when route added using express its takes time to access the api

**Comment by MuradCade** [comment]
there were require error of module express in the index file but its fixed successfully

**Comment by MuradCade** [comment]
there were require error of module express in the index file but its fixed successfully

**Comment by DevopsTech10** [comment]
index.js  in route file

**Comment by DevopsTech10** [comment]
db folder has many access in server and router folder

**Comment by MuradCade** [comment]
bugs fixed in index file

**Comment by MuradCade** [comment]
bugs fixed
